name: Type check (make)
on:
  workflow_call:
    inputs:
      erlang_version:
        required: true
        type: string
      elixir_version:
        required: true
        type: string
jobs:
  type-check-plugin:
    name: Type check plugins
    strategy:
      fail-fast: false
      matrix:
        plugin:
          # These are using plugin-specific test jobs.
          - rabbit
          # @todo We are getting errors because of wrong types
          # in the eetcd dep. But upgrading requires using gun 2.0,
          # which we can't because another app's dep, emqtt, requires
          # gun 1.3.x. So for now we don't type check this plugin.
          #- rabbitmq_peer_discovery_etcd
    uses: ./.github/workflows/test-make-target.yaml
    with:
      erlang_version: ${{ inputs.erlang_version }}
      elixir_version: ${{ inputs.elixir_version }}
      metadata_store: khepri # Not actually used.
      make_target: dialyze
      plugin: ${{ matrix.plugin }}
