name: Test Authentication/Authorization backends via mutiple messaging protocols
on:
  push:
    branches:
      - main
      - v4.0.x
    paths:
      - 'deps/rabbit/src/rabbit_auth**'
      - 'deps/rabbit/src/rabbit_access_control**'
      - 'deps/rabbitmq_auth_**'
      - 'deps/rabbitmq_management/src/**'
      - 'deps/rabbitmq_management/priv/**'
      - 'deps/rabbitmq_management/selenium/**'
      - 'scripts/**'
      - .bazelrc
      - .bazelversion
      - BUILD.*
      - '*.bzl'
      - '*.bazel'
      - .github/workflows/test-authnz.yaml
  pull_request:
    paths:
      - 'deps/rabbit/**'
      - 'deps/rabbitmq_auth_/**'
      - 'deps/rabbitmq_mqtt/**'
      - 'deps/rabbitmq_management/selenium/full-suite-authnz-messaging'
      - 'deps/rabbitmq_management/selenium/suites/authnz-messaging/**'
      - 'deps/rabbitmq_management/selenium/test/authnz-msg-protocols/**'
      - .github/workflows/test-authnz.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
