name: Test Management UI with Selenium
on:
  push:
    branches:
      - main
      - v4.0.x
      - bump-otp-for-oci
      - bump-rbe-*
      - bump-rules_erlang
    paths:
      - 'deps/rabbitmq_management/src/**'
      - 'deps/rabbitmq_management/priv/**'
      - 'deps/rabbitmq_web_dispatch/src/**'
      - 'scripts/**'
      - .bazelrc
      - .bazelversion
      - BUILD.*
      - '*.bzl'
      - '*.bazel'
      - 'selenium/**'
      - .github/workflows/test-management-ui.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
