name: Run tests (make)
on:
  workflow_call:
    inputs:
      erlang_version:
        required: true
        type: string
      elixir_version:
        required: true
        type: string
      metadata_store:
        required: true
        type: string
      mixed_clusters:
        required: true
        type: boolean
jobs:
  test-rabbit:
    name: Test rabbit
    strategy:
      fail-fast: false
      matrix:
        make_target:
          - parallel-ct-set-1
          - parallel-ct-set-3
          - ct-feature_flags
    uses: ./.github/workflows/test-make-target.yaml
    with:
      erlang_version: ${{ inputs.erlang_version }}
      elixir_version: ${{ inputs.elixir_version }}
      metadata_store: ${{ inputs.metadata_store }}
      mixed_clusters: ${{ inputs.mixed_clusters }}
      make_target: ${{ matrix.make_target }}
      plugin: rabbit

  test-rabbitmq-mqtt:
    name: Test rabbitmq_mqtt
    uses: ./.github/workflows/test-make-target.yaml
    with:
      erlang_version: ${{ inputs.erlang_version }}
      elixir_version: ${{ inputs.elixir_version }}
      metadata_store: ${{ inputs.metadata_store }}
      mixed_clusters: ${{ inputs.mixed_clusters }}
      make_target: parallel-ct-set-1
      plugin: rabbitmq_mqtt

  test-plugin:
    name: Test plugins
    strategy:
      fail-fast: false
      matrix:
        plugin:
          - amqp10_client
          - amqp_client
          - rabbitmq_cli
          - rabbitmq_management
    uses: ./.github/workflows/test-make-target.yaml
    with:
      erlang_version: ${{ inputs.erlang_version }}
      elixir_version: ${{ inputs.elixir_version }}
      metadata_store: ${{ inputs.metadata_store }}
      mixed_clusters: ${{ inputs.mixed_clusters }}
      make_target: tests
      plugin: ${{ matrix.plugin }}
